[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.16" # Lock in a compiler version to avoid via_ir assembly dropping bug below 0.8.14
# Configuration Values to Ensure Yul is inlined nicely, and optimized well
optimizer = true
optimizer_runs = 50000
via_ir = true
# Configuration to ensure strict fuzzing testing
fuzz_runs = 1000


[optimizer_details.yul_details]
stack_allocation = true
optimizer_steps = true

[rpc_endpoints]
mainnet = ""
optimism = ""
arbitrum = ""
polygon = ""
