[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.17" # Lock in a compiler version to avoid via_ir assembly dropping bug below 0.8.14
# Configuration Values to Ensure Yul is inlined nicely, and optimized well
optimizer = true
optimizer_runs = 200
via_ir = true
# Configuration to ensure strict fuzzing testing
fuzz_runs = 1000

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true

[rpc_endpoints]
mainnet = ""
optimism = ""
arbitrum = ""
polygon = ""
